
#----------Instillinger: Boks på toppen av side----------------------------------------------------------------------
name: Sok-xxxx Emnetittel #Emnetittel
semester: Høst/Vår 20xx 
image: tema.jpg




#--------------Avanserte instillinger---------------------------------------------------------------------
topbox-farge: 00617f

contentbox-farge: ffff;
contentbox-skygge: 0px 0px 100px 0px rgba(50, 50, 50, 1)

bakgrunn: ./assets/img/bakgrunn.jpg
bakgrunn-farge: 

#Farge tekst
primaerfarge: 007396 #Farge overskrifter
sekundaerfarge: #Farge generell tekst
linkfarge: f2a900 #Farge linker

uitlogo: ./assets/img/uit.png
#Skal stå tom
title: ''



#-------------IKKE SLETT---------------------------------------------------------------------
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
   auto_ids: true
